### ISSUE TITLE
1.6.0-pre6

### ISSUE THREAD

**Issue by TorbenK** [TorbenK/TK.CustomMap#248]
Please test 1.6.0-pre1 as this has the updated dependencies. Thanks!

Edit: 1.6.0-pre2 includes missing dependencies
Edit: 1.6.0-pre3 fixes a bug on Android, which causes the `IOnMapReadyCallback` to be invoked twice.
Edit: 1.6.0-pre4 fixes incorrect/missing disposing in Android Renderer.
Edit: 1.6.0-pre5 fixes possible memory leak in iOS renderer. Added UWP binaries to package(basic preview - shoutout to @jfversluis)
Edit: 1.6.0-pre6 includes missing UWP dependencies

**Comment by angelru** [comment]
Hello, not available for PCL?

```
 Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'TK.CustomMap 1.6.0-pre1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
```

**Comment by TorbenK** [comment]
@angelru You can add it to your PCL project, but since the library is targeting .netstandard 1.1 now, you need to switch to profile 111, which is the default when creating a new XF PCL project. I would recommend switching to netstandard though. You can read more here:

https://xamarinhelp.com/upgrade-pcl-net-standard-class-library/
https://blog.xamarin.com/net-standard-library-support-for-xamarin/

**Comment by straiser** [comment]
In 1.6.0-pre2  I have got error when try to add Route:
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: An item with the same key has already been added. Key: TK.CustomMap.Overlays.TKRoute

**Comment by TorbenK** [comment]
does this also happen in the sample? Is this in iOS or Android?

**Comment by straiser** [comment]
I don't tested sample yet. I just created new project with one page and try to add route.
I tested only in Android so far.

**Comment by TorbenK** [comment]
make sure all api keys are setup correctly. I am able to add routes without any problem.

**Comment by straiser** [comment]
You are right. I copied wrong direction key. Sorry for trouble.

**Comment by vincentcastagna** [comment]
Got the same error but when trying to add a pin ...
My CustomPin extends TKCustomMapPin. 

Strange behavior Im' on it since 3 hours ... **But it's working** with my own builded dlls from release 1.5.1 

```
 System.ArgumentException: An item with the same key has already been added. Key: Project.Core.Models.Map.CustomPin
10-24 01:24:22.232 I/MonoDroid( 2203):   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000bb] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-24 01:24:22.232 I/MonoDroid( 2203):   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
10-24 01:24:22.232 I/MonoDroid( 2203):   at TK.CustomMap.Droid.TKCustomMapRenderer+<AddPin>d__34.MoveNext () [0x001e9] in <faa94377908740ef83f3381c7ae5d6e5>:0 
10-24 01:24:22.232 I/MonoDroid( 2203): --- End of stack trace from previous location where exception was thrown ---
```

**Comment by TorbenK** [comment]
Thanks. That's a bug with the `IOnMapReadyCallback` invoked twice. It is fixed in 1.6.0-pre3, which is already available.

**Comment by straiser** [comment]
I still have issue #214  When I reopen map with pins it crash with following error: 
```
System.NullReferenceException: Object reference not set to an instance of an object.
10-24 10:59:46.085 I/MonoDroid(15724):   at TK.CustomMap.Droid.TKCustomMapRenderer.UpdatePins (System.Boolean firstUpdate) [0x00057] in <1dbaac14fe454b1f8b5988cfb8273367>:0 
10-24 10:59:46.085 I/MonoDroid(15724):   at TK.CustomMap.Droid.TKCustomMapRenderer.FormsMapPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x00020] in <1dbaac14fe454b1f8b5988cfb8273367>:0 
10-24 10:59:46.085 I/MonoDroid(15724):   at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
10-24 10:59:46.085 I/MonoDroid(15724):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:137 
10-24 10:59:46.085 I/MonoDroid(15724):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:388 
10-24 10:59:46.085 I/MonoDroid(15724):   at TK.CustomMap.TKCustomMap.OnPropertyChanged (System.String propertyName) [0x00000] in <23b849d4cf5740ee91a00410699e5a23>:0 
10-24 10:59:46.085 I/MonoDroid(15724):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x000f4] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:593 
10-24 10:59:46.085 I/MonoDroid(15724):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:390 
10-24 10:59:46.085 I/MonoDroid(15724):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:174 
10-24 10:59:46.085 I/MonoDroid(15724):   at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:56 
10-24 10:59:46.085 I/MonoDroid(15724):   at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__47_0 () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:551 
10-24 10:59:46.085 I/MonoDroid(15724):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <484cd191a834496c85d38d0e644a42c4>:0 
10-24 10:59:46.085 I/MonoDroid(15724):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <484cd191a834496c85d38d0e644a42c4>:0 
10-24 10:59:46.085 I/MonoDroid(15724):   at (wrapper dynamic-method) System.Object:3b9b3b59-f8e8-4ca0-acc2-b1707fcafb2d (intptr,intptr)
```

**Comment by TorbenK** [comment]
can you share your project. Not able to reproduce this at all.

**Comment by straiser** [comment]
For this moment I can't, but I will try give you something. Interesting thing is that it works fine if I add custom pins in Code Behind. Error is only when I do this by binding ( pins are the same in both cases).

**Comment by TorbenK** [comment]
I may found the cause of the weird Android vodoo exceptions. Please try pre4.

**Comment by vincentcastagna** [comment]
@TorbenK  Fix in 1.6.0-pre3 works for error :

> Item with the same key has already been added

. Thanks for your time ! 

@straiser are you sure your collection of pins is init in your viewModel constructor when reloading Map ?
`  _pins = new ObservableCollection<CustomPin>();`

**Comment by straiser** [comment]
@TorbenK  pre4 works ok, thank you very much for quick update :)

 But I started to testing it on iOS and I noticed strange thing: map is so slow on simulator. Anyone noticed something similat?  Moving in map is so slow - I must wait few second to move on map. I don't know is this  simulator  thing, but I will try to check it on real device.

**Comment by TorbenK** [comment]
@straiser 

great that the fix works. Yes, the new simulators are indeed very slow, especially when using `MKMapView`. I recommend using a device for testing.
